[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    let g:molokai_original = 1
'''

