[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.vim']

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = 'call echodoc#enable()'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_source = 'denite.vim'
hook_source = 'source ~/.vim/rc/plugins/unite.rc.vim'
hook_add = '''
    nnoremap <silent> ,f :<C-u>Unite file<CR>
    nnoremap <silent> ,d :<C-u>Unite directory<CR>
    nnoremap <silent> ,g :<C-u>Unite grep<CR>
    nnoremap <silent> <C-k> :<C-u>Unite change jump<CR>
    nnoremap <silent> <C-t> :<C-u>Unite -auto-resize -select=`tabpagenr()-1` tab<CR>
    " Tag jump.
    nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
            \ ":\<C-u>UniteWithCursorWord -buffer-name=tag -immediately
            \  tag tag/include\<CR>"
    nnoremap <silent><expr> tp  &filetype == 'help' ?
            \ ":\<C-u>pop\<CR>" : ":\<C-u>Unite jump\<CR>"
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('python3')"
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    nnoremap <silent>,df :<C-u>Denite file_rec<CR>
    nnoremap <silent> / :<C-u>Denite -buffer-name=search line<CR>
    nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search line<CR>
    nnoremap <silent> n :<C-u>Denite -buffer-name=search -resume -mode=normal<CR>
'''

[[pluhins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_mao = {n = '<Plug>'}
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repo = 'davidhalter/jedi-vim'
if = "!has('nvim')"
on_ft = 'python'
hook_source = '''
    autocmd FileType python setlocal omnifunc=jedi#completions
    source ~/.vim/rc/plugins/jedi-vim.rc.vim
'''

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
hook_source = '''
    if 1
    autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
    endif 
'''

[[plugins]]
repo = 'kana/vim-smartchr'
on_event = 'InsertCharPre'
hook_source = '''
inoremap <expr>= smartchr#loop(' = ', ' == ', '=')
inoremap <expr>, smartchr#loop(', ', ',')
inoremap <expr>、 smartchr#loop('，')
inoremap <expr>。 smartchr#loop('.')
'''

[[plugins]]
repo = 'nixprime/cpsm'
on_source = 'denite.nvim'

[[pluginss]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
    xmap I <Plug>(niceblock-I)
    xmap A <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
    nmap <silent>j <Plug>(accelerated_jk_gj)
    nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'lambdalisue/vim-findent'

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'
hook_add = 'let g:vinarise_enable_auto_detect = 1'

