[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.vim']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_source = 'denite.vim'
hook_source = 'source ~/.vim/rc/plugins/unite.rc.vim'
hook_add = '''
    nnoremap <silent> <C-k>
            \ :<C-u>Unite change jump<CR>
    nnoremap <silent> <C-t>
            \ :<C-u>Unite -auto-resize -select=`tabpagenr()-1` tab<CR>
    " Tag jump.
    nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
            \ ":\<C-u>UniteWithCursorWord -buffer-name=tag -immediately
            \  tag tag/include\<CR>"
    nnoremap <silent><expr> tp  &filetype == 'help' ?
            \ ":\<C-u>pop\<CR>" : ":\<C-u>Unite jump\<CR>"
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('python3')"
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/plugins/denite.rc.vim'
hook_add = '''
    nnoremap <silent> ;r
        \ :<C-u>Denite -buffer-name=register unite:register neoyank<CR>
    nnoremap <silent> [Window]<Space>
        \ :<C-u>Denite file_rec:~/.vim/rc<CR>
    nnoremap <silent> / :<C-u>Denite -buffer-name=search line<CR>
    nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search line<CR>
    nnoremap <silent> [Window]s :<C-u>Denite file_point file_mru
        \ `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>
    nnoremap <silent> [Window]n :<C-u>Denite dein<CR>
    nnoremap <silent> [Window]g :<C-u>Denite ghq<CR>
    nnoremap <silent> ;g :<C-u>Denite -buffer-name=search -no-empty grep<CR>
    nnoremap <silent> n :<C-u>Denite -buffer-name=search -resume -mode=normal<CR>
    nnoremap <silent> ft :<C-u>Denite filetype<CR>
    nnoremap <silent> <C-t> :<C-u>Denite unite:tab -select=`tabpagenr()-1` -mode=normal<CR>
'''

[[pluhins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_if = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_mao = {n = '<Plug>'}
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['neocomplete.vim', 'deoplete.nvim']

[[plugins]]
repo = 'davidhalter/jedi-vim'
if = "!has('nvim')"
on_ft = 'python'
hook_source = 'source ~/.vim/rc/plugins/jedi-vim.rc.vim'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
hook_source = '''
    autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'kana/vim-smartchr'
on_event = 'InsertEnter'
hook_source = '''
inoremap <buffer> <expr>= smartchr#loop(' = ', ' == ', '=')
inoremap <buffer> <expr>, smartchr#loop(', ', ',')
inoremap <buffer> <expr>、 smartchr#loop('，')
inoremap <buffer> <expr>。 smartchr#loop('.')
'''

[[plugins]]
repo = 'nixprime/cpsm'
on_source = 'denite.nvim'
