[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'

[[plugins]]
repo = 'cespare/vim-toml'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'set laststatus=2'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:molokai_original = 1
'''

[[plugins]]
repo = 'tomasr/molokai'
