[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
hook_source = '''
    let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
    let g:deoplete#sources#clang#clang_header = '/usr/local/opt/llvm/lib/clang'

    let g:deoplete#sources#clang#flags = ['-x', 'c++', '-std=c++']
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    source ~/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
on_source = 'denite.nvim'
hook_add = '''
    nnoremap <silent>N :<C-u>tabnew<CR>:<C-u>Deol zsh<CR>
    nnoremap <silent>[Space]s :<C-u>Deol zsh<CR>
'''
hook_source = '''
    set shell=zsh
    source ~/.vim/rc/plugins/deol.rc.vim
'''
